### ISSUE TITLE
你这个插件网易官方授权了吗？

### ISSUE THREAD

**Issue by jjeejj** [sigoden/netease-music-crx#1]

**Comment by sigoden** [comment]
没呢，这个会有多大影响？

**Comment by jjeejj** [comment]
你看看 网易云音乐官方的服务条款
![jietu20180110-230624](https://user-images.githubusercontent.com/15176971/34779447-30629768-f65b-11e7-91cb-68b4dff73553.jpg)


这只是一部分。。。

这些东西自己玩玩就好了........

**Comment by leopku** [comment]
@jjeejj 现在这不就是玩玩，还怎么滴了？

**Comment by MeGuMinEx** [comment]
？
