### ISSUE TITLE
显示不全，底部有左右滑动栏

### ISSUE THREAD

**Issue by cshijiel** [sigoden/netease-music-crx#15]
![image](https://user-images.githubusercontent.com/8501605/141427396-e0ecc97e-5e50-40f8-a61c-811a50601161.png)

另外建议推出docker部署版

**Comment by sigoden** [comment]
这是浏览器扩展，不是独立应用。没法docker

你用的什么浏览器？

**Comment by cshijiel** [comment]
Microsoft Edge
版本 95.0.1020.44 (官方内部版本) (x86_64)
Mac版本

**Comment by sigoden** [comment]
Chrome中popup页面按规范是宽不超过800px，高不超过600px。

我在Windows版本的Edge中测试过是没有问题的

不知道Mac版本Edge中popup页面的宽最多是多少？

**Comment by cshijiel** [comment]
刚检查了，是浏览器全局缩放导致的，切换到100%恢复正常。
如果支持Chrome app运行就好了。。。

**Comment by sigoden** [comment]
作成扩展就可以少开一个应用了。因为对我来说浏览器总是开着的。

**Comment by cshijiel** [comment]
好的 依然感谢
