### ISSUE TITLE
有可能兼容键盘的媒体热键吗？

### ISSUE THREAD

**Issue by oasisfeng** [sigoden/netease-music-crx#24]
在普通 tab 中打开 music.163.com 播放的音乐，可以通过键盘的媒体热键控制，但通过插件播放时似乎不行。

**Comment by ahaooahaz** [comment]
+1, ubuntu 只能控制暂停播放，上/下一首用不了, 要是能设置快捷键就好了

**Comment by oasisfeng** [comment]
能否考虑发布一个包含此优化的新版本到 Chrome Web Store？谢谢！
