### ISSUE TITLE
之前好像有我的歌单,现在没有了?

### ISSUE THREAD

**Issue by seekwe** [sigoden/netease-music-crx#3]
rt

ps. 一般小打小闹网易云是不会管的,话说还有人弄了终端版网易云呢

**Comment by sigoden** [comment]
不清楚你描述的状况，你能截个图吗？

**Comment by sigoden** [comment]
该 Issue 无法重现，也没有其它人追加反馈。所以我准备关闭。

如果再遇到类似问题，请再开 Issue 并提供更详细的信息。
